### ISSUE TITLE
Update Minecraft description to include old world download

### ISSUE THREAD

**Issue by egee-irl** [Egeeio/egeeio-website#49]
The old world is hosted on my old Yandex Disk. Not sure if that is the safest place to store it. At any rate, people ask for the old world somewhat regularly so let's put a link in the server description.

**Comment by MattSturgeon** [comment]
Might make sense just to use a generic download site like mediafire.com

**Comment by GhostSquad57** [comment]
I would suggest either Dropbox or Mega

**Comment by GhostSquad57** [comment]
Mediafire has a ton a malicious ads
