### ISSUE TITLE
Game server icons are off-centered on mobile

### ISSUE THREAD

**Issue by PerplexativeKhat** [Egeeio/egeeio-website#85]
The icons for the Game servers section are slightly to the left when viewing in portrait mode on mobile.

**Comment by StripedMonkey** [comment]
![screenshot from 2017-03-03 19-01-10](https://cloud.githubusercontent.com/assets/8009284/23573607/2dbcc84c-0045-11e7-878e-cdd3cd916303.png)

**Comment by PerplexativeKhat** [comment]
Thank you
